[build]
  publish = "dist"
  command = "rm -rf node_modules package-lock.json && npm install --ignore-scripts && npx nuxt prepare && npm run generate"

[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--no-audit --no-fund"
  NPM_CONFIG_CACHE = "/tmp/.npm"
  NUXT_TELEMETRY_DISABLED = "1"
  CI = "true"

[context.production]
  command = "rm -rf node_modules package-lock.json && npm install --ignore-scripts && npx nuxt prepare && npm run generate"

[context.deploy-preview]
  command = "rm -rf node_modules package-lock.json && npm install --ignore-scripts && npx nuxt prepare && npm run generate"

# Proxy auth paths to Keycloak server (equivalent to Vercel rewrites)
[[redirects]]
  from = "/auth/*"
  to = "https://casino-citizen.eks-dev01.gigndvr.com/auth/:splat"
  status = 200
  force = true
  headers = {X-Forwarded-Host = ":host"}

# Proxy realms paths to Keycloak server
[[redirects]]
  from = "/realms/*"
  to = "https://casino-citizen.eks-dev01.gigndvr.com/realms/:splat"
  status = 200
  force = true
  headers = {X-Forwarded-Host = ":host"}

# Assets redirect (if needed)
[[redirects]]
  from = "/assets/*"
  to = "https://kc-theme-demo-site.vercel.app/assets/:splat"
  status = 200
  force = true

# SPA fallback - must be last
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
